---
dist: trusty
cache: pip
sudo: required

# notifications:
#   slack:
#     rooms:
#       - "$SLACK_ROOM"
#     on_pull_requests: false
#     on_success: change

services:
  - docker

env:
  - SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-21-a \
    SNAPSHOT_TYPE=swift-4.2-branch

before_install:
  - sudo apt-get install shellcheck
  - sudo pip install yamllint
  - git clone https://github.com/IBM/pattern-ci

before_script:
  - "./pattern-ci/tests/shellcheck-lint.sh containers iOS"
  - "./pattern-ci/tests/yaml-lint.sh containers iOS"

jobs:
  include:
    - install: ./pattern-ci/scripts/install-swift.sh
      script: ./tests/build-local.sh
    - install: ./pattern-ci/scripts/install-minikube.sh
      script: ./tests/deploy-minikube.sh
